<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0-windows\Services\MonitoringService.exe.runtimeconfig.json" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MonitoringContracts\MonitoringContracts.csproj" />
    <ProjectReference Include="..\MonitoringService\MonitoringService.csproj" OutputItemType="None" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <!-- Ensure MonitoringService builds first and its outputs are copied before SystemMonitorApp -->
  <Target Name="EnsureMonitoringServiceBuilt" BeforeTargets="Build">
    <MSBuild Projects="..\MonitoringService\MonitoringService.csproj" Targets="Build" Properties="Configuration=$(Configuration);Platform=$(Platform)" />
  </Target>

</Project>
