<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.0" />
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MonitoringContracts\MonitoringContracts.csproj" />
	</ItemGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="taskkill /f /fi &quot;imagename eq MonitoringService*&quot; 2&gt;nul&#xD;&#xA;exit 0" />
	</Target>

</Project>