/**
 * FileComparerApp - A file comparison application
 * 
 * Description: This enum contains the types of comparison results that can be generated by the FileComparer application.
 * 
 * Author: Adam Chen
 * Date: 2025/07/25
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FileComparerApp.Models
{
    public enum CompareItemType
    {
        Unchanged,
        Added,
        Removed,
        Modified
    }
}
